### AppController
@baseUrl = http://localhost:3000

###Consulta mensagem
GET {{baseUrl}}/recados/
###Cria mensage
POST {{baseUrl}}/recados/
Content-Type: application/json

{
  "text": "324",
  "from": "2342",
  "to": "2342342"
}
### Atualiza mensagem
PATCH {{baseUrl}}/recados/6876f4ecd22ca8828ddb8526
Content-Type: application/json

{
  "text": "324",
  "from": "oioioioi",
  "to": "2342342"
}
###Apaga um mensagem
DELETE {{baseUrl}}/recados/6876f4fad22ca8828ddb852a

